export type { IFeedGateway } from './IFeedGateway'
export type { FeedState, FeedItem } from './feed.reducer'
export type { Dependencies } from './feed.saga'
export type { Action } from './feed.actions'
export { feedReducer, RequestStatus } from './feed.reducer'
export { feedSaga } from './feed.saga'
export { publicActions as feedActions, ActionType } from './feed.actions'
export * from './feed.selectors'
