export const env = {
  API_V1_URL: process.env.API_V1_URL as string,
  API_KEY: process.env.API_KEY as string,
  GOOGLE_MAP_API_KEY: process.env.GOOGLE_MAP_API_KEY as string,
  SENTRY_DSN: process.env.SENTRY_DSN as string,
  ADMIN_ASSO_URL: process.env.ADMIN_ASSO_URL as string,
  SERVER_URL: process.env.SERVER_URL as string,
  FIREBASE_API_KEY: process.env.FIREBASE_API_KEY as string,
  FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN as string,
  FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL as string,
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID as string,
  FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET as string,
  FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID as string,
  FIREBASE_APP_ID: process.env.FIREBASE_APP_ID as string,
  FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_ID as string,
}
