export const FirebaseEvents = [
  'View__LoginOrSignup__',
  'Action__LoginOrSignup__ValidatePhone',
  'Action__Login__Connection',
  'Action__Login__PasswordForgotten',
  'Action__SignUp__CreateAccount',
  'Action__SignUp__ValidateSMSCode',
  'Action__SignUp__ResendSMSCode',
  'Action__SignUp__ValidatePassword',
  'Action__LoginOrSignup__Cancel',
  'View__Workshop',
  'Action__Workshop__Participate',
  'Action__Workshop__Card',
  'Action__Workshop__Dismiss',
  'Action__Workshop__DismissNotInterested',
  'Action__Workshop__DismissAlready',
  'Action__Workshop__DismissDiscover',
  'Action__Map__Search',
  'Action__Map__PanZoom',
  'Action__Map__Geolocation',
  'View__Feed',
  'Action__Feed__ListItem',
  'Action__Feed__MapItem',
  'View__POIs',
  'Action__POIs__ListItem',
  'Action__POIs__MapItem',
  'View__Messages',
  'Action__Messages__WriteMessage',
  'View__ActionMenu',
  'Action__ActionMenu__CreateAction',
  'Action__ActionMenu__CreateEvent',
  'Action__ActionMenu__Ambassador',
  'Action__ActionMenu__Workshop',
  'Action__ActionMenu__GoodWaves',
  'Action__ActionMenu__Donate',
] as const

export type FirebaseEvent = typeof FirebaseEvents[number]

export type FirebaseProps = Record<string, string>
