import {
  Bathtub,
  CardGiftcard,
  Explore,
  Home,
  LocalDrink,
  LocalHospital,
  LocalLaundryService,
  LocalMall,
  Lock,
  MoreHoriz,
  People,
  Restaurant,
  Spa,
  Stars,
  SvgIconComponent,
  Wc,
} from '@material-ui/icons'
import { POICategory } from 'src/core/api'
import { texts } from 'src/i18n'

export const poiIcons: Record<POICategory, SvgIconComponent> = {
  0: MoreHoriz,
  1: Restaurant,
  2: Home,
  3: LocalHospital,
  5: Explore,
  7: People,
  8: Stars,
  40: Wc,
  41: LocalDrink,
  42: Bathtub,
  43: LocalLaundryService,
  6: Spa,
  61: LocalMall,
  63: Lock,
  62: CardGiftcard,
}

export const poiLabels: Record<POICategory, string> = {
  0: texts.types.pois.other,
  1: texts.types.pois.eating,
  2: texts.types.pois.sleeping,
  3: texts.types.pois.healing,
  5: texts.types.pois.orientation,
  7: texts.types.pois.reintegration,
  8: texts.types.pois.partners,
  40: texts.types.pois.toilets,
  41: texts.types.pois.fountains,
  42: texts.types.pois.showers,
  43: texts.types.pois.laundries,
  6: texts.types.pois.well_being,
  61: texts.types.pois.clothes,
  62: texts.types.pois.donation_box,
  63: texts.types.pois.cloakroom,
}
