name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
        check-latest: true

    - run: echo "::set-output name=dir::$(yarn cache dir)"
      id: yarn-cache-dir-path
    - uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          yarn-

    - run: yarn install --frozen-lockfile
    - run: yarn test
    - run: yarn build
